#docker-compose up -d
#docker-compose -f "docker-compose.yml" up -d --build web
version: "3.8"
services:
  main:
    build:
      context: .
      dockerfile: docker/main.Dockerfile
    environment:
    - ENV=development
    - REDIS_URL=redis
    volumes:
    - ./:/host_machine/:rw
#    hostname: "mycontainer"
    depends_on:
    - redis

  redis:
    image: redis:latest

#volumes:
#  mysql_data: { driver: local }